#!/bin/sh

alpha='dd'
background='#282a36'
selection='#44475a'
comment='#6272a4'

yellow='#f1fa8c'
orange='#ffb86c'
red='#ff5555'
magenta='#ff79c6'
blue='#65737e'
cyan='#8be9fd'
green='50fa7b'
black='#343d46'
white='#c0c5ce'

i3lock \
  --insidever-color=$selection$alpha \
  --insidewrong-color=$selection$alpha \
  --inside-color=$selection$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ring-color=$blue$alpha \
  --line-uses-ring \
  --keyhl-color=$magenta$alpha \
  --bshl-color=$orange$alpha \
  --separator-color=$selection$alpha \
  --verif-color=$green \
  --wrong-color=$red \
  --layout-color=$black \
  --date-color=$white \
  --time-color=$white \
  --screen 1 \
  --blur 1 \
  --clock \
  --indicator \
  --time-str="%H:%M" \
  --date-str="%A, %e-%m-%Y" \
  --verif-text="Checking" \
  --wrong-text="Wrong pswd" \
  --noinput="No Input" \
  --lock-text="Locking" \
  --lockfailed="Lock Failed" \
  --radius=150 \
  --ring-width=10 \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys \
  --time-font="Monocraft Nerd Font" \
  --date-font="Monocraft Nerd Font" \
  --layout-font="Monocraft Nerd Font" \
  --verif-font="Monocraft Nerd Font" \
  --wrong-font="Monocraft Nerd Font" \

# These last five lines are commented because they concern the font you want to use.
# JetBrainsMono Nerd Font is the font that was used in the screenshot.
# To specify a favorite font, just uncomment the five lines and replace the parameter with the font you prefer.
