unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-a
set -g mode-keys vi
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g set-clipboard on
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g default-terminal "screen-256color"
set -g pane-border-style fg='#6272a4'
set -g pane-active-border-style fg='#ff79c6'
set -g message-style bg='#44475a',fg='#8be9fd'
set -g status-style bg='#44475a',fg='#bd93f9'
set -g status-interval 1
set -g status-left '#[bg=#f8f8f2]#[fg=#282a36]#{?client_prefix,#[bg=#ff79c6],} 󱓇  '
set -ga status-left '#[bg=#44475a]#[fg=#ff79c6] #{?window_zoomed_flag,↕ ,  }'
set-window-option -g window-status-style fg='#bd93f9',bg=default
set-window-option -g window-status-current-style fg='#ff79c6',bg='#282a36'
set -g window-status-current-format "#[fg=#44475a]#[bg=#bd93f9]#[fg=#44475a]#[bg=#8be9fd] #I #W  #[fg=#bd93f9]#[bg=#44475a]"
set -g window-status-format "#[fg=#f8f8f2]#[bg=#44475a]#I #W #[fg=#44475a] "
set -g status-right '#[fg=#343d46,bg=#8be9fd]#[fg=#f8f8f2,bg=#343d46] #{battery_icon_status} #{battery_percentage} '
set -ga status-right '#[fg=#65737e,bg=#ff79c6]#[fg=#f8f8f2,bg=#65737e] 󰃭 %d-%b '
set -ga status-right '#[fg=#c0c5ce,bg=#44475a]#[fg=#44475a,bg=#c0c5ce] 󱑒 %H:%M '
set -g status-left-length 200
set -g status-right-length 200
set -g status-position top

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'
set -g @t-bind 'K'
set -g @t-fzf-find-binding 'ctrl-l:change-prompt(  )+reload(fd -H -d 2 -t d -E .Trash . ~)'
set -g @t-fzf-prompt '  '
set -g @tmux-last-color on
set -g @tmux-last-pager 'less -r'
set -g @tmux-last-pager 'less'
set -g @tmux-last-prompt-pattern ' '
set -g @tmux-nerd-font-window-name-shell-icon ''
set -g @tmux-nerd-font-window-name-show-name false
set -g @yank_selection_mouse 'clipboard' # or 'primary' or 'secondary'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'mskelton/tmux-last' # <prefix>t
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-battery'

run '.config/tmux/plugins/tpm/tpm'
